### ISSUE TITLE
Problem with saving model in python3

### ISSUE THREAD

**Issue by thran** [riga/tfdeploy#11]
I am getting following error `TypeError: must be str, not bytes` at line https://github.com/riga/tfdeploy/blob/master/tfdeploy.py#L176.

It seem that [pickle.dump](https://docs.python.org/3.2/library/pickle.html#pickle.dump) and pickle.load requires files opened as binary in python3.

**Comment by riga** [comment]
Thanks for opening this ticket. Should be solved by a6bce00. Can you confirm this?

**Comment by thran** [comment]
Confirmed (for python 3)
