### ISSUE TITLE
reduction functions failed when reduction_indices is numpy.int32

### ISSUE THREAD

**Issue by ugtony** [riga/tfdeploy#21]
When running the tfdeploy model, I got this error

File "/home/sutony/git/facenet/src/align/tfdeploy.py", line 1838, in Max
    axis=tuple(reduction_indices)
TypeError: 'numpy.int32' object is not iterable

It happens when the reduction_indices is an integer
```python
#does not work when reduction_indices is an numpy integer (e.g., np.int32)
tuple(reduction_indices)  
```
I changed the code in Max() and Sum() to make the program runnable, but the code is not neat and I'm not sure if it works for other cases.
```python
if not isinstance(reduction_indices, np.ndarray):
    return np.amax(a, axis=reduction_indices, keepdims=keep_dims),
else:
    return np.amax(a, axis=tuple(reduction_indices), keepdims=keep_dims),
```

The other reduction functions might cause the same error.

**Comment by riga** [comment]
Thanks for reporting this.

The `isinstance` query cannot be avoided imho to ensure the interface between tf and np is working in all situations.
