### ISSUE TITLE
Error while loading : AttributeError: Can't get attribute 'Mul' on <module 'tfdeploy

### ISSUE THREAD

**Issue by All-Ki** [riga/tfdeploy#35]
so i get : Traceback (most recent call last):
  File "game.py", line 7, in <module>
    model = td.Model("model.pkl")
  File "C:\Users\admin\Miniconda3\lib\site-packages\tfdeploy.py", line 113, in __init__ 
 self.load(path)
  File "C:\Users\admin\Miniconda3\lib\site-packages\tfdeploy.py", line 169, in load
    roots = pickle.load(f)

AttributeError: Can't get attribute 'Mul' on <module 'tfdeploy' from 'C:\\Users\\admin\\Miniconda3\\lib\\site-packages\\tfdeploy.py'>. 

Looks like it is because of a deprecation of tensorflow. Gotta update this!

**Comment by All-Ki** [comment]
F*ck me, problem from my side... And i can't remove it. Great.

**Comment by nguyenhoanganh2002** [comment]
I encountered 1 similar problem. How to solve it?
