### ISSUE TITLE
Comparison to the C++ API

### ISSUE THREAD

**Issue by raddy** [riga/tfdeploy#9]
Have you compared how this compares to model evaluation via the c++ API?

I'd think the most common optimization-of-evaluation use case would be generating highly portable C code for production systems where there's no desire to include the 100+ MB of tensorflow libs. (Assuming you could get superior performance with only Eigen maybe)

**Comment by riga** [comment]
You mean the tensorflow C++ API? No, I didn't check that yet, but I think there's not much Python overhead in tensorflow as well as in *most* ops in tfdeploy and numpy. So concerning performance, tfdeploy vs. tensorflow (Python) should be roughly equivalent to tfdeploy vs. tensorflow (C++). But as I said, I'm not 100% sure about this. Tests are welcome =)
